name: project
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.1
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  flutter_secure_storage: ^7.0.1
  flutter_svg: 
  flutter_switch: ^0.3.2
  shared_preferences: ^2.0.15
  flutter_calendar_week: ^3.0.0
  dio: ^4.0.6
  conditional_builder_null_safety: ^0.0.6
  intl: ^0.17.0
  flutter_calendar_carousel: ^2.4.1
  date_time_picker: ^2.1.0
  get: ^4.5.0
  google_maps_flutter: ^2.2.2
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  http: ^0.13.5
  url_launcher: ^6.0.11
  http_parser: ^4.0.2
  webview_flutter: ^3.0.4
  flutter_typeahead: ^4.0.0
  image_pixels: ^3.0.0
  permission_handler: ^10.2.0
  location: ^5.0.0-dev.8
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  flutter_launcher_icons: ^0.11.0
#  firebase_storage: ^10.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  pin_code_fields: ^7.3.0


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/home/
    - assets/icons/delivery/
    - assets/icons/chat/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
